/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#a43716",
        "on-primary": "#ffffff",
        "primary-container": "#c54f2c",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdbd1",
        "primary-fixed-dim": "#ffb5a0",
        "on-primary-fixed": "#3b0900",
        "on-primary-fixed-variant": "#862201",
        "inverse-primary": "#ffb5a0",
        "secondary": "#2c657b",
        "on-secondary": "#ffffff",
        "secondary-container": "#aee5fe",
        "on-secondary-container": "#2f677d",
        "secondary-fixed": "#bce9ff",
        "secondary-fixed-dim": "#98cee7",
        "on-secondary-fixed": "#001f29",
        "on-secondary-fixed-variant": "#0a4d62",
        "tertiary": "#8b4c18",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a8642e",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-fixed-dim": "#ffb785",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#703703",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#faf9f5",
        "surface-dim": "#dbdad6",
        "surface-bright": "#faf9f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f0",
        "surface-container": "#efeeea",
        "surface-container-high": "#e9e8e4",
        "surface-container-highest": "#e3e2df",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#58423c",
        "outline": "#8b716a",
        "outline-variant": "#dfc0b7",
        "inverse-surface": "#2f312e",
        "inverse-on-surface": "#f2f1ed",
        "surface-variant": "#e3e2df",
        "surface-tint": "#a73918",
        "background": "#faf9f5",
        "on-background": "#1b1c1a",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "unit": "8px",
        "margin-mobile": "20px",
        "section-gap": "120px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "1.5", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}
